# Generated by Django 6.0.1 on 2026-01-31 07:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('scheduled', 'Scheduled'), ('rejected', 'Rejected')], default='applied', max_length=12, verbose_name='Staus')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Applied')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated')),
                ('note', models.TextField(verbose_name='Note')),
            ],
            options={
                'ordering': (['company'],),
            },
        ),
    ]
