# Generated by Django 6.0.1 on 2026-02-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['company']},
        ),
    ]
